# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            On the way 
tagline:          'day day up...'
description:      '      To be a better man'

author:
  name:           'gosaturn'
  url:            https://github.com/gosaturn

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : gosaturn 
